
HUBOT_AUTH_ADMIN=orie EXPRESS_USER=orie EXPRESS_PASSWORD=orie EXPRESS_STATIC=WebApp/dist FIREBASE_URL=$HUBOT_FIREBASE_APP_URL FIREBASE_SECRET=$HUBOT_FIREBASE_SECRET bin/hubot -n RxRemedi --adapter shell
