#!/usr/bin/env bash

export HUBOT_AUTH_ADMIN=YOUR_NAME

#Secret
export HUBOT_FIREBASE_SECRET=YOUR_SECRET

#Database
export HUBOT_FIREBASE_APP_URL=https://YOUR_APP.firebaseio.com/hubot

#Chat room schema
export HUBOT_FIREBASE_ROOMS_PATH=/applicationStores/chatRooms
export HUBOT_FIREBASE_CHAT_PATH=/chatMessages

#Message schema
export HUBOT_FIREBASE_MSG_USERID_PATH=/userId
export HUBOT_FIREBASE_MSG_USERNAME_PATH=/userProfile/userName
export HUBOT_FIREBASE_MSG_CONTENT_PATH=/message



# rhc env set HUBOT_FIREBASE_SECRET=$HUBOT_FIREBASE_SECRET HUBOT_FIREBASE_APP_URL=$HUBOT_FIREBASE_APP_URL HUBOT_FIREBASE_ROOMS_PATH=$HUBOT_FIREBASE_ROOMS_PATH HUBOT_FIREBASE_CHAT_PATH=$HUBOT_FIREBASE_CHAT_PATH HUBOT_FIREBASE_MSG_USERID_PATH=$HUBOT_FIREBASE_MSG_USERID_PATH HUBOT_FIREBASE_MSG_USERNAME_PATH=$HUBOT_FIREBASE_MSG_USERNAME_PATH HUBOT_FIREBASE_MSG_CONTENT_PATH=$HUBOT_FIREBASE_MSG_CONTENT_PATH -a YOUR_APP
